### ISSUE TITLE
The default permission setup might make it impossible to ever upgrade the token contract   

### ISSUE THREAD

**Issue by Comdex** [MinaFoundation/mina-fungible-token#112] opened 2024-11-28 09:17 UTC
The default permission settings of the current token standard contract are configured this way:

https://github.com/MinaFoundation/mina-fungible-token/blob/7f2427afd75e3b7aeda29cf3ec9e240790c10c20/FungibleToken.ts#L73-L77

The `access` permission is set to `Proof,` and if I am not mistaken, this requires the corresponding `AccountUpdate` of the token contract to include a proof in order to be accepted by the network. However, the permission for `setVerificationKey` will change to Signature after the protocol upgrade. This means that updating the VerificationKey will require signature authorization. Since an `AccountUpdate` cannot simultaneously include both proof and signature authorization, and with updates to permissions being disallowed, this would likely result in the token contract being permanently unupgradable.

The `access` permission has the highest priority, which means that when it is set to `Proof`, other permissions set to` Signature` will become invalid

**Comment by L-as** [comment] 2024-11-30 13:01
This is a very good point.

**Comment by L-as** [comment] 2024-11-30 13:02
Unless I’m missing something this isn’t fixable and is a limitation of Mina

**Comment by Comdex** [comment] 2024-11-30 13:35
> Unless I’m missing something this isn’t fixable and is a limitation of Mina.

I think that makes sense. We’ll probably need to make some changes at the protocol level to fix this.

**Comment by mitschabaude** [comment] 2024-12-05 14:33
DAMN that's a great find @Comdex. I agree it needs a protocol-level fix.

@mrmr1993 @nholland94 hope you saw this -- once there is a vk-breaking upgrade, all contracts with access=proof are broken, because the verification key update (using a signature) can't go through, and neither can any proof for the outdated vk

**Comment by andrewferrone** [comment] 2024-12-05 20:23
Is a short-term workaround to change the `access` permission to `Signature`? @kantp

**Comment by kantp** [comment] 2024-12-05 20:40
With `access` set to `signature`, other things would stop working, so unfortunately we can't do that. I think what we need to do is have a method that changes the verification key, using a proper access control (like what @dfstio is working on for the NFT standard). Then, we need to change the permissions to change the verification key to `proof`, instead of `impossibleDuringCurrentVersion`.

**Comment by kantp** [comment] 2024-12-05 20:46
Unfortunately, we can't set the permissions to change the verification key to `proof` with the contract as it is right now, because the `updateVerificationKey()` method does not control who calls it. So we need to change that, and only then change the permissions.

**Comment by kantp** [comment] 2024-12-06 10:20
For anyone following this: there is also a discussion on Discord, see  https://discord.com/channels/484437221055922177/1311633212769960009/1311633212769960009.

At the moment, we're trying to get a short term solution to this for the fungible tokens, while also looking at the necessary protocol changes to fix the root cause. I'll update as we progress.

**Comment by mrmr1993** [comment] 2024-12-08 17:44
We've been tracking this issue for a while on the O(1) side. There's an easy fix, and it's part of the plan for the next hard fork.
Feel free to use the access permission however you need, the upgrade mechanism will handle it in a coherent way.

**Comment by kantp** [comment] 2024-12-09 16:57
Thanks @mrmr1993, that's good news!

What I still want to change is adding access management to the updateVerificationKey method, in order to enable making the contract upgradable before a breaking change to the protocol. That way, people can upgrade to keep up to date with fixes and improvements in o1js.

**Comment by kantp** [comment] 2024-12-10 17:13
> What I still want to change is adding access management to the updateVerificationKey method, in order to enable making the contract upgradable before a breaking change to the protocol. That way, people can upgrade to keep up to date with fixes and improvements in o1js.

See #113.

**Comment by kantp** [comment] 2024-12-18 09:37
With #113, `deploy()` now has a flag `allowUpdates` to switch between upgradable and not upgradable (during the current protocol version). The documentation recommends allowing updates during the current protocol version. Updating the verification key requires a permission from the admin contract, so that is customisable (the example contract uses a signature from the admin).

Together with @mrmr1993's message above that the `access` permission issue will be fixed with the next protocol update, I think we can close this issue.

**Closed by kantp** 2024-12-18 09:37 UTC
